export { default as Logo } from './Logo.svg'
export { default as Restauranfood } from './restauranfood.jpg'
export { default as Lemondessert } from './lemon_dessert.jpg'
export { default as Greeksalad } from './greek_salad.jpg'
export { default as Dishicon } from './Dish_icon.svg'
export { default as Mario } from './Mario2.jpg'
export { default as Restaurant } from './restaurant.jpg'
